base_config:
- ../config/default.yaml

job_name: release_debug 

model:
  name: slurpp_pipeline
  pretrained_path: stable-diffusion-2
  pretrained_path2: marigold-depth-v1-0
  latent_scale_factor: 0.18215

trainer:
  color_space: srgb  # "srgb" or "linear"
  inputs: ["u"] 
  inputs2: ["u"]
  output: ["clear"]   
  output2: ["bc", "ill"]
  upsample: 1
  num_hour_between_val: 2
  num_hour_between_real_vis: 2

dual: true
rgb_loss: True
reconstruction_loss: True
one_step: True

lr: 1e-5

lr_scheduler:
  name: IterExponential
  kwargs:
    total_iter: 50000
    final_ratio: 0.01
    warmup_steps: 100
  
dataloader:
  image_size: 384
  num_workers: 2
  effective_batch_size: 2 # 32
  max_train_batch_size: 2
  val_size: 20
  train_vis_size: 20

